services:
  postgres_db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mail_local:
    image: axllent/mailpit:v1.29
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped
    environment:
      - MP_DATA_FILE=/data/mailpit.db
    volumes:
      - mailpit_data:/data

  rabbitmq:
    image: rabbitmq:4.2.4-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pg_data:
  redis_data:
  rabbitmq_data:
  mailpit_data:
